language: node_js
node_js:
  - 12
stage: Tests
before_script:
  - yarn
  - yarn add coveralls
jobs:
  include:
    - stage: Tests
      node_js: "12"
      script: yarn test | coveralls
    - stage: Eslint
      node_js: "12"
      before_script:
        - yarn
      script: yarn run eslint